### ISSUE TITLE
User management -> name fields

### ISSUE THREAD

**Issue by antonym8** [antonym8/Match-my-university#3]
List page shows first name and last name columns but create page shows only name field

![Screenshot (418)](https://github.com/antonym8/Match-my-university/assets/142376069/7c8cd9c4-ab3f-49cb-82f9-e847affec183)
![Screenshot (419)](https://github.com/antonym8/Match-my-university/assets/142376069/f93eb927-2d36-4f07-9cc0-974688e4fc9d)

**Comment by aarthim8** [comment]
fixed
