### ISSUE TITLE
Static privacy & policy

### ISSUE THREAD

**Issue by antonym8** [antonym8/Match-my-university#54]
![Screenshot (459)](https://github.com/antonym8/Match-my-university/assets/142376069/e5cae4cb-b01a-4a75-8efb-8a7ee7282f75)
![Screenshot (460)](https://github.com/antonym8/Match-my-university/assets/142376069/574b56d1-9a24-443c-88eb-5fc19c203ae2)

**Comment by M8Balaji** [comment]
Fixed
