### ISSUE TITLE
Static terms and conditions

### ISSUE THREAD

**Issue by antonym8** [antonym8/Match-my-university#56]
![Screenshot (462)](https://github.com/antonym8/Match-my-university/assets/142376069/8c4b43aa-2f57-484a-9c55-4b90d677c2b8)
![Screenshot (463)](https://github.com/antonym8/Match-my-university/assets/142376069/ef8fe318-0929-4d80-9583-de10d54334be)

**Comment by M8Balaji** [comment]
Fixed
